<?php
    return[
        'FCM_SERVER_KEY' => 'AAAAd09yvqo:APA91bEMG0BagvHNORg5lku1UXikP7ffJSuK_2lk_Tf5PLGV1RVAqcURN1_iUTH3n5Km2ZXxGc3GiMaf5sutO9ttYYHuI6A-TLQW0MKZKUUAHc-dbF7wGf23kjBbUaoPSmPzjW7GXX3-',
        'FCM_NOTIFICATION_DEFAULT_TITLE' => 'NOTIFICATION FROM' . env('APP_URL'),
        'FCM_NOTIFICATION_DEFAULT_BODY' => 'A MESSAGE SENT FROM ' . env('APP_URL'),
        'FCM_NOTIFICATION_DEFAULT_IMAGE' => '',
        'FCM_NOTIFICATION_DEFAULT_TO' => 'all',
    ];
