<?php
    return[
        'NOTIFICATIONS_COMMAND_EXECUTED' => 'NOTIFICATONS COMMAND EXECUTED',
        'NOTIFICATIONS_SUCCESS_MESSAGE' => 'NOTIFICATONS WHERE SUCCESSFULLY SENT',
        'NOTIFICATIONS_FAILURE_MESSAGE' => 'NOTIFICATIONS FAILED TO BE SENT',
    ];